global:
  scrape_interval: 15s

storage:
  tsdb:
    out_of_order_time_window: 30m

otlp:
  promote_resource_attributes:
    - service.name
    - service.version
  keep_identifying_resource_attributes: true
